shortly/urls.py
from django.contrib import admin
from django.urls import include, path 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shortly/', include('shortly_app.urls')),
]

shortly_app/urls.py
from django.urls import path

from .views import DetailView, NewView, LinksView, TopView, ShortlyView

urlpatterns = [
    path('', TopView.as_view(), name='index'),
    path('list', LinksView.as_view(), name='list_short_url'),
    path('<int:shortly_id>/detail', DetailView.as_view(), name='detail'),
    path('<int:shortly_id>', ShortlyView.as_view(), name='follow_link'),
    path('new', NewView.as_view(), name='new'),
]

shortly_app/models.py
from django.db import models

# Create your models here.
class TopShortlyManager(models.Manager):
    def top(self, count=5):
        return super().get_queryset().filter(visit_counter__gt=0).order_by('-visit_counter')[:count]
    
class Shortly(models.Model):
    link = models.URLField(unique=True)
    visit_counter = models.PositiveIntegerField(default=0)

    objects = TopShortlyManager()

    def update_counter(self):
        self.visit_counter += 1 
        self.save()

shortly_app/forms.py
from django import forms
from .models import Shortly

class ShortlyForm(forms.ModelForm):
    class Meta:
        model = Shortly
        fields = ('link',)

shortly_app/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import CreateView
from .forms import ShortlyForm
from .models import Shortly

# Create your views here.
class TopView(ListView):
    context_object_name = 'top'
    queryset = Shortly.objects.top()
    template_name = 'shortly_app/index.html'

class LinksView(ListView):
    model = Shortly
    template_name = 'shortly_app/link_list.html'
    paginate_by = 7

class ShortlyView(View):
    
    def get(self, request, *args, **kwargs):
        shortly = get_object_or_404(Shortly, pk=kwargs['shortly_id'])
        shortly.update_counter()
        return redirect(shortly.link)
        

class DetailView(TemplateView):
    template_name = 'shortly_app/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['target'] = get_object_or_404(Shortly, pk=kwargs['shortly_id'])
        return context

class NewView(CreateView):
    form_class = ShortlyForm
    template_name = 'shortly_app/new.html'
    success_url = 'detail'

    def get_success_url(self):
        return reverse(self.success_url, args=(self.object.id,))

shortly_app/templates/shortly_app/base.html
{% load static from staticfiles %}

<!DOCTYPE HTML>
<html lang="UK">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
	  <title>{% block meta_title %}{% endblock meta_title %}</title>

	  <!-- Include Styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
  </head>

  <body>    
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Shortly</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}">TOP-5</a></li>
            <li><a href="{% url 'list_short_url' %}">Link's list</a></li>
            <li><a href="{% url 'new' %}">New Shortly</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        
        <h1>Shortly - {% block title %}{% endblock title %}</h1>
        <!--<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>-->
      </div>
      {% block content %}{% endblock content %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

  </body>
</html>

shortly_app/templates/shortly_app/detail.html
{% extends "shortly_app/base.html" %}

{% block meta_title %}Detail{% endblock meta_title %}


{% block title %}detail about link{% endblock title %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Info</h2>    
        </div>
        <div class="panel-body">
            <b>Short link : </b> <a href="{% url 'follow_link' target.pk %}">/{{ target.pk }}</a> 
        </div>
        <div class="panel-body">
            <b>Full url : </b> {{ target.link }}
        </div>
        <div class="panel-body">
            <b>Visit count : </b> {{ target.visit_counter }}
        </div>
    </div>
{% endblock content %}

shortly_app/templates/shortly_app/index.html
{% extends "shortly_app/base.html" %}

{% block meta_title %}TOP-5{% endblock meta_title %}


{% block title %}TOP-5 visited links{% endblock title %}

{% block content %}
    <div class="panel-body">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr class="bg-red text-white">
                    <th>#</th>
                    <th>Link</th>
                    <th>Visited</th>
                </tr>
            </thead>
            <tbody>
                {% if top %}
                    {% for item in top %}
                        <tr>
                            <td><a class="btn btn-default btn-xs" href="{% url 'detail' item.pk %}" role="button">Detail</a></td>
                            <td>{{ item.link }}</td>
                            <td>{{ item.visit_counter }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td></td>
                        <td><center><b>No visited links yet</b></center></td>
                        <td></td>
                    </tr>                                                  
                {% endif %}
            </tbody>                
        </table>
    </div>
{% endblock content %}

shortly_app/templates/shortly_app/link_list.html
{% extends "shortly_app/base.html" %}

{% block meta_title %}Link's list{% endblock meta_title %}


{% block title %}Link's list{% endblock title %}
{% block content %}
<div class="panel-body">
    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr class="bg-red text-white">
                <th>#</th>
                <th>Link</th>
            </tr>
        </thead>
        <tbody>
            {% for shortly in shortly_list %}
                <tr>
                    <td><a class="btn btn-default btn-xs" href="{% url 'detail' shortly.pk %}" role="button">Detail</a></td>
                    <td>{{ shortly.link }}</td>
                </tr>
            {% endfor %}
        </tbody>                
    </table>
</div>
<nav aria-label="Page navigation">
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
</nav>

{% endblock content %}

shortly_app/templates/shortly_app/new.html
{% extends "shortly_app/base.html" %}

{% load bootstrap3 %}

{% block meta_title %}New link{% endblock meta_title %}


{% block title %}NEW link{% endblock title %}
{% block content %}
<form method="POST">
    {% csrf_token %}
      {% bootstrap_form form %}
    <button type="submit" class="btn btn-red">Add</button>
</form>
{% endblock content %}